FROM continuumio/miniconda3:4.9.2

RUN apt-get update --fix-missing && \
    apt-get install -y gcc && \
    apt-get install -y g++ && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN conda install libmagic && \
    conda clean -afy

RUN pip install aiohttp --no-cache-dir && \
    pip install git+https://github.com/ironmussa/dateinfer.git --no-cache-dir && \
    pip install git+https://github.com/ironmussa/Optimus.git@develop-3.0 --no-cache-dir















