FROM rapidsai/rapidsai:cuda10.2-runtime-ubuntu18.04-py3.7

RUN apt-get update --fix-missing && \
    apt-get install -y gcc && \
    apt-get install -y g++ && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN conda install libmagic && \
    conda clean -afy

RUN pip install aiohttp --no-cache-dir && \
    pip install cupy-cuda102 --no-cache-dir && \
    pip install dask-cuda --no-cache-dir && \
    pip install git+https://github.com/hi-primus/optimus.git@develop-22.6 --no-cache-dir
