DROP TABLE oracle_main;

create table oracle_main (
	id INT,
	first_name VARCHAR(50),
	last_name VARCHAR(50),
	email VARCHAR(50),
	gender VARCHAR(50),
	ip_address VARCHAR(20)
);

insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (1, 'Maximo', 'Caren', 'mcaren0@cbc.ca', 'Male', '209.1.158.216');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (2, 'Ricki', 'Thurstan', 'rthurstan1@youtu.be', 'Male', '23.152.245.234');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (3, 'Norris', 'Renshaw', 'nrenshaw2@vk.com', 'Male', '87.212.118.45');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (4, 'Becky', 'Fintoph', 'bfintoph3@trellian.com', 'Female', '91.101.188.181');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (5, 'Billye', 'Kayzer', 'bkayzer4@domainmarket.com', 'Female', '146.203.129.66');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (6, 'Darb', 'Savile', 'dsavile5@pinterest.com', 'Male', '35.79.51.126');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (7, 'Jefferey', 'Massenhove', 'jmassenhove6@surveymonkey.com', 'Male', '209.231.75.39');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (8, 'Grenville', 'Atwood', 'gatwood7@purevolume.com', 'Male', '185.29.226.232');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (9, 'Loni', 'Vell', 'lvell8@liveinternet.ru', 'Female', '163.113.221.34');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (10, 'Mimi', 'Salliss', 'msalliss9@amazonaws.com', 'Female', '69.146.93.12');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (11, 'Kathye', 'Meneux', 'kmeneuxa@bandcamp.com', 'Female', '28.131.230.1');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (12, 'Fanya', 'Domb', 'fdombb@yellowpages.com', 'Female', '104.129.156.18');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (13, 'Valry', 'Pleace', 'vpleacec@cnbc.com', 'Female', '58.65.74.179');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (14, 'Agna', 'Smyth', 'asmythd@sbwire.com', 'Female', '10.86.114.228');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (15, 'Harli', 'Kerswill', 'hkerswille@china.com.cn', 'Female', '193.118.137.171');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (16, 'Lorianna', 'Buddle', 'lbuddlef@dmoz.org', 'Female', '90.180.35.11');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (17, 'Daphna', 'Ateridge', 'dateridgeg@princeton.edu', 'Female', '173.154.179.159');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (18, 'Raimund', 'McKeowon', 'rmckeowonh@amazon.co.uk', 'Male', '119.74.87.37');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (19, 'Estelle', 'Drogan', 'edrogani@yellowbook.com', 'Female', '64.154.195.178');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (20, 'Jamil', 'O''Luby', 'jolubyj@macromedia.com', 'Male', '221.219.247.128');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (21, 'Melisse', 'Gillmor', 'mgillmork@europa.eu', 'Female', '57.167.169.66');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (22, 'Sheree', 'Twitchings', 'stwitchingsl@archive.org', 'Female', '37.3.73.76');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (23, 'Amby', 'Wann', 'awannm@msn.com', 'Male', '173.237.89.144');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (24, 'Lou', 'Exon', 'lexonn@auda.org.au', 'Male', '174.76.85.150');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (25, 'Isidore', 'Sango', 'isangoo@dailymail.co.uk', 'Male', '12.240.145.56');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (26, 'Jerrilee', 'Inglesent', 'jinglesentp@netvibes.com', 'Female', '110.124.128.232');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (27, 'Fairlie', 'Walker', 'fwalkerq@g.co', 'Male', '249.51.140.34');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (28, 'Reilly', 'Akhurst', 'rakhurstr@geocities.jp', 'Male', '133.199.185.232');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (29, 'Bartholomeo', 'Stanway', 'bstanways@goo.gl', 'Male', '114.215.117.83');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (30, 'Christoph', 'Costan', 'ccostant@naver.com', 'Male', '149.9.219.17');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (31, 'Idaline', 'Vigars', 'ivigarsu@wsj.com', 'Female', '69.178.12.156');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (32, 'Uta', 'MacCaffrey', 'umaccaffreyv@marketwatch.com', 'Female', '216.158.24.22');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (33, 'Moss', 'Tiller', 'mtillerw@cargocollective.com', 'Male', '27.83.121.109');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (34, 'Rosaleen', 'Boshier', 'rboshierx@si.edu', 'Female', '252.229.223.67');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (35, 'Angus', 'Moroney', 'amoroneyy@webnode.com', 'Male', '170.208.176.114');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (36, 'Helenelizabeth', 'Antosch', 'hantoschz@slashdot.org', 'Female', '117.88.186.244');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (37, 'Haskel', 'Grelik', 'hgrelik10@umich.edu', 'Male', '7.198.86.232');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (38, 'Abrahan', 'Jentin', 'ajentin11@nydailynews.com', 'Male', '29.110.178.206');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (39, 'Valentin', 'Tregonna', 'vtregonna12@jigsy.com', 'Male', '61.160.247.42');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (40, 'Dorothea', 'Guiver', 'dguiver13@netlog.com', 'Female', '34.119.209.175');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (41, 'Raynor', 'Reisenstein', 'rreisenstein14@github.com', 'Male', '40.251.224.20');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (42, 'Haskel', 'Brabham', 'hbrabham15@slideshare.net', 'Male', '150.245.141.111');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (43, 'Nalani', 'Vitler', 'nvitler16@toplist.cz', 'Female', '44.211.242.67');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (44, 'Jehu', 'Wrought', 'jwrought17@yellowpages.com', 'Male', '204.88.103.87');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (45, 'Nikaniki', 'Chesshyre', 'nchesshyre18@redcross.org', 'Female', '235.98.123.94');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (46, 'Emlynne', 'Radolf', 'eradolf19@github.io', 'Female', '218.33.154.41');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (47, 'Olivia', 'Goulborn', 'ogoulborn1a@typepad.com', 'Female', '206.125.157.80');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (48, 'Leon', 'Kryska', 'lkryska1b@goo.ne.jp', 'Male', '70.18.171.205');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (49, 'Ellette', 'Bleiman', 'ebleiman1c@com.com', 'Female', '126.155.139.179');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (50, 'Bryan', 'Rosle', 'brosle1d@yellowpages.com', 'Male', '166.149.226.240');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (51, 'Merell', 'Emmatt', 'memmatt1e@marketwatch.com', 'Male', '62.195.106.52');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (52, 'Emmey', 'Walsh', 'ewalsh1f@ted.com', 'Female', '72.110.121.150');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (53, 'Emogene', 'Corssen', 'ecorssen1g@msn.com', 'Female', '164.213.58.2');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (54, 'Korney', 'Lynett', 'klynett1h@shareasale.com', 'Female', '237.38.62.143');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (55, 'Lefty', 'Stallybrass', 'lstallybrass1i@ovh.net', 'Male', '5.69.108.84');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (56, 'Deck', 'Dranfield', 'ddranfield1j@godaddy.com', 'Male', '16.116.45.229');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (57, 'Inglis', 'Mosco', 'imosco1k@google.cn', 'Male', '70.112.38.120');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (58, 'Aldo', 'Ruddle', 'aruddle1l@webmd.com', 'Male', '73.254.163.151');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (59, 'Laurel', 'Kix', 'lkix1m@joomla.org', 'Female', '41.114.223.48');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (60, 'Emma', 'McDade', 'emcdade1n@mysql.com', 'Female', '103.157.231.99');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (61, 'Fianna', 'Arnout', 'farnout1o@blog.com', 'Female', '178.215.172.38');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (62, 'Randi', 'Gerrad', 'rgerrad1p@1und1.de', 'Male', '99.216.43.154');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (63, 'Timotheus', 'Daoust', 'tdaoust1q@toplist.cz', 'Male', '52.94.10.82');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (64, 'Cybil', 'Chadbourne', 'cchadbourne1r@joomla.org', 'Female', '180.204.166.157');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (65, 'Marga', 'Biernacki', 'mbiernacki1s@shop-pro.jp', 'Female', '166.117.215.91');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (66, 'Tyne', 'Forge', 'tforge1t@people.com.cn', 'Female', '193.100.59.255');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (67, 'Dov', 'Gyurkovics', 'dgyurkovics1u@hud.gov', 'Male', '89.89.204.34');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (68, 'Sigfrid', 'Harmer', 'sharmer1v@a8.net', 'Male', '127.252.117.211');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (69, 'Blinni', 'Fewster', 'bfewster1w@washington.edu', 'Female', '136.214.101.121');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (70, 'Jimmy', 'Amos', 'jamos1x@newsvine.com', 'Male', '193.131.43.128');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (71, 'Stephannie', 'Pendleberry', 'spendleberry1y@sohu.com', 'Female', '88.93.210.114');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (72, 'Sergio', 'Burgen', 'sburgen1z@over-blog.com', 'Male', '183.216.201.149');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (73, 'Barbara', 'Shellcross', 'bshellcross20@technorati.com', 'Female', '5.197.222.126');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (74, 'Beatrix', 'Hartshorne', 'bhartshorne21@biglobe.ne.jp', 'Female', '143.27.33.120');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (75, 'Marina', 'Attle', 'mattle22@thetimes.co.uk', 'Female', '113.75.188.34');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (76, 'Rosalinda', 'Alejo', 'ralejo23@wix.com', 'Female', '228.39.179.128');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (77, 'Vanessa', 'Swedeland', 'vswedeland24@theguardian.com', 'Female', '189.111.101.29');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (78, 'Jacques', 'Gutowski', 'jgutowski25@163.com', 'Male', '5.220.17.14');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (79, 'Eryn', 'Insole', 'einsole26@unesco.org', 'Female', '102.218.189.96');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (80, 'Joshia', 'Colleer', 'jcolleer27@pen.io', 'Male', '197.183.37.12');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (81, 'Vidovic', 'Tutchings', 'vtutchings28@si.edu', 'Male', '132.14.7.92');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (82, 'Rivkah', 'Ricardo', 'rricardo29@who.int', 'Female', '202.67.66.103');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (83, 'Marc', 'Turrill', 'mturrill2a@constantcontact.com', 'Male', '170.79.246.5');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (84, 'Rees', 'Booij', 'rbooij2b@mysql.com', 'Male', '212.83.75.212');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (85, 'Mattias', 'O''Doireidh', 'modoireidh2c@devhub.com', 'Male', '75.43.240.228');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (86, 'Jermaine', 'Beaney', 'jbeaney2d@hud.gov', 'Male', '207.40.156.4');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (87, 'Siegfried', 'Twigger', 'stwigger2e@whitehouse.gov', 'Male', '64.65.149.61');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (88, 'Wynn', 'Lugsdin', 'wlugsdin2f@phoca.cz', 'Male', '155.130.221.51');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (89, 'Peadar', 'Tobias', 'ptobias2g@example.com', 'Male', '216.110.86.103');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (90, 'Nehemiah', 'Kinloch', 'nkinloch2h@tuttocitta.it', 'Male', '31.123.183.87');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (91, 'Dyanna', 'Yegorovnin', 'dyegorovnin2i@miibeian.gov.cn', 'Female', '19.35.193.43');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (92, 'Ash', 'Simenet', 'asimenet2j@exblog.jp', 'Male', '108.55.14.197');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (93, 'Thibaud', 'Brettle', 'tbrettle2k@netvibes.com', 'Male', '216.63.91.181');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (94, 'Clim', 'Germon', 'cgermon2l@europa.eu', 'Male', '173.159.23.111');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (95, 'Yvor', 'Bellingham', 'ybellingham2m@wired.com', 'Male', '129.249.175.224');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (96, 'Onfroi', 'Bim', 'obim2n@wiley.com', 'Male', '236.64.170.39');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (97, 'Conan', 'Cawston', 'ccawston2o@about.com', 'Male', '111.175.210.95');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (98, 'Norry', 'Olander', 'nolander2p@indiatimes.com', 'Female', '6.68.10.229');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (99, 'Christophe', 'Simms', 'csimms2q@army.mil', 'Male', '170.203.25.9');
insert into modelo.oracle_main (id, first_name, last_name, email, gender, ip_address) values (100, 'Marven', 'Lockie', 'mlockie2r@eventbrite.com', 'Male', '216.238.156.217');